
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv




class MFStructure:
    def __init__(self, cust):
        self.cust = cust
        self.count_1_quant = 0
        self.sum_2_quant = 0
        self.max_3_quant = 0

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    sales_rows = cur.fetchall()
    _global = []
    
    h_table = []
    for row in sales_rows:
        found = False
        for entry in h_table:
            if entry.cust == row['cust']:
                found = True
                for att,val in vars(entry).items():
                    if att=='sum_quant':
                        entry.sum_quant += row['quant']
                    if att=='min_quant':
                        if entry.min_quant > row['quant']:
                            entry.min_quant = row['quant']
                    if att=='max_quant':
                        if entry.max_quant < row['quant']:
                            entry.max_quant = row['quant']
                    if att=='count_quant':
                        entry.count_quant += 1
                break
        if not found:
            new_entry = MFStructure(row['cust'])
            for att,val in vars(new_entry).items():
                    if att=='sum_quant':
                        new_entry.sum_quant = row['quant']
                    if att=='min_quant':
                        new_entry.min_quant = row['quant']
                    if att=='max_quant':
                        new_entry.max_quant = row['quant']
                    if att=='count_quant':
                        new_entry.count_quant = 1
            h_table.append(new_entry)
    
    
    # Scan for grouping variable 1
    for row in sales_rows:
        if row['state'] == 'NY':
            for entry in h_table:
                if entry.cust == row['cust']:
                    entry.count_1_quant += 1
                    break

    # Scan for grouping variable 2
    for row in sales_rows:
        if row['state'] == 'NJ':
            for entry in h_table:
                if entry.cust == row['cust']:
                    entry.sum_2_quant += row['quant']
                    break

    # Scan for grouping variable 3
    for row in sales_rows:
        if row['state'] == 'CT':
            for entry in h_table:
                if entry.cust == row['cust']:
                    entry.max_3_quant = max(entry.max_3_quant, row['quant'])
                    break

        
    for entry in h_table:
        if entry.count_1_quant*2<entry.max_3_quant:
            _global.append({
            'cust': entry.cust, 'count_1_quant': entry.count_1_quant, 'sum_2_quant': entry.sum_2_quant, 'max_3_quant': entry.max_3_quant
    })       
    
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    